export const ERROR_MESSAGES = {
    1: "Error interno — algo falló dentro del contrato.",
    3: "Ya se ha inicializado.",
    4: "Acción no autorizada.",
    5: "Entrada inválida.",
    8: "La cantidad no puede ser negativa.",
    9: "Error de permiso — se requiere aprobación.",
    10: "Balance insuficiente.",
    12: "Error de desbordamiento.",

    // --- Game logic ---
    200: "El juego no existe.",
    201: "La configuración de la apuesta no existe.",
    202: "No estás autorizado para apostar en este juego privado.",
    203: "No tienes suficiente balance para apostar en este juego privado.",
    204: "El juego ya ha finalizado.",
    205: "Los Summiters no pueden apostar.",
    206: "Configuración de juego público no encontrada.",
    207: "El juego ya ha comenzado.",
    208: "El juego ya está activo.",
    209: "El juego aún no ha comenzado.",
    210: "El juego ya ha sido configurado.",
    211: "El juego aún no ha terminado.",
    212: "No estás autorizado para enviar un resultado.",
    213: "La evaluación del juego ya ha terminado.",
    214: "Resultado del juego no encontrado.",
    215: "El usuario no puede votar.",
    216: "El juego no ha sido pausado.",
    217: "No se encontró la apuesta.",
    218: "Nada para reclamar.",
    219: "El usuario ya reclamó.",
    220: "El juego ha sido pausado.",
    221: "El juego ya ha sido ejecutado.",
    222: "No eres administrador.",
    223: "No hay suficiente stake para realizar esta acción.",
    224: "Firmante desconocido.",
    225: "El resultado del juego ya ha sido establecido.",
    226: "Apuesta no encontrada.",

    // --- Faltantes del enum ---
    227: "La fase de envío del juego ya ha finalizado.",
    228: "No se necesita envío.",
    249: "El resultado del juego ya fue ejecutado.",
    260: "La configuración no está activa.",
    261: "El usuario ya ha votado.",
    299: "El juego no tiene resultado."
};
