// errors.js
export const ERROR_MESSAGES = {
    1: "Internal error — something went wrong inside the contract.",
    3: "Already initialized.",
    4: "Unauthorized action.",
    5: "Invalid input.",
    8: "Amount cannot be negative.",
    9: "Allowance error — approval required.",
    10: "Insufficient balance.",
    12: "Overflow error.",
    200: "Game does not exist.",
    201: "Bet setting does not exist.",
    202: "You are not allowed to bet on this private game.",
    203: "Not enough balance to bet in private game.",
    204: "The game has already finished.",
    205: "Summiters are not allowed to bet.",
    206: "Public game settings not found.",
    207: "The game has already started.",
    208: "The game is already active.",
    209: "The game has not started yet.",
    210: "The game has already been set.",
    211: "The game has not finished yet.",
    212: "You are not allowed to submit a result.",
    213: "Game assessment has already finished.",
    214: "Game result not found.",
    215: "User cannot vote.",
    216: "The game has not been paused.",
    217: "No bet found.",
    218: "Nothing to claim.",
    219: "User already claimed.",
    220: "The game has been paused.",
    221: "The game has already been executed.",
    222: "Not admin.",
    223: "Not enough stake to perform this action.",
    224: "Unknown signer.",
    225: "Game result has already been set.",
    226: "Bet not found."
};
